### PR TITLE
FAST.Farm case creation class

### PR DESCRIPTION
**Pull request by rthedin**
Addition of a class for complete case creation. 
Includes the following:
- Ability to setup sweeps on TI, wind speed, shear, wind direction, yaw, AeroDyn/AeroDisk model, ElastoDyn/SimplifiedElastoDyn model
- Several sanity checks of setup
- Setup of low- and high-res boxes from TurbSim if that is the case
- Creation (and automatic submission) of SLURM scripts for each step
- Creation of all input files necessary

Does not include:
- Post processing

Still a draft PR because I will include examples. Will make a regular PR when that is done.

### CODE REVIEW

**Comment by ebranlard** [comment]
Thanks for doing that, let me know when it's ready to review. 
If it makes sense to add tests or examples that would be great. 

The examples in the folder examples should be run by the unittests. If some of them require binaries, then we'll have to skip parts of the examples.

**Comment by andrew-platt** [comment]
@jjonkman, could you review?

**Comment by rthedin** [comment]
Update: This PR also includes a new class that will write LES inputs for sampling LES inflow from AMR-Wind. An example is provided in the examples directory.

**Comment by rthedin** [comment]
@ebranlard This is ready to be merged, pending @jjonkman's review.

**Comment by ebranlard** [comment]
I'll merge this now, some things to consider for a future pull request: 
- add unittests in`tests`
- Some of the examples added could be made "runable", possibly with a minimum working example (say, less than 100kb). This way, the example would be run by the unittest.

**Pull request merged**
